# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: ["--autofix", "--indent=4", "--no-sort-keys"]
-   repo: local
    hooks:
    -   id: ruff-formatter
        name: ruff-formatter
        entry: ruff format
        args: ["."]
        language: system
        pass_filenames: false
    -   id: isort
        name: isort
        entry: isort
        args: ["."]
        language: system
        pass_filenames: false
    -   id: flake8
        name: flake8
        entry: flake8
        args: [".", "--ignore=E501"]
        language: system
        pass_filenames: false
